#!/usr/bin/env php
<?php
set_time_limit(0);

require dirname(__FILE__).'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Conv\Command\CheckCommand;
use Conv\Command\ReflectCommand;

$app = new Application();
$app->add(new CheckCommand());
$app->add(new ReflectCommand());
$app->run();
