#!/usr/bin/env php
<?php
set_time_limit(0);

require dirname(__FILE__).'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$composerData = json_decode(file_get_contents('composer.json'));
$name = key(current($composerData->autoload));
$dir = current(current($composerData->autoload));

$app = new Application();

$app->add(new \Howyi\Conv\DebugCommand\CheckAlterCommand());
$app->add(new \Howyi\Conv\DebugCommand\ReflectCommand());
$app->add(new \Howyi\Conv\DebugCommand\SetupCommand());
$app->run();
